### ISSUE TITLE
Opinion about the Fade animation

### ISSUE THREAD

**Issue by TerminalVibes** [violin-suzutsuki/LinoriaLib#30]
I'm not all that sure about the Fade animation added recently. I'd argue that animation isn't always the way to go, since the rest of the entire UI Library doesn't use it (ex: Toggles, Dropdowns, and etc. all don't have animation). It takes away the instant and responsive feeling the library used to give.

Is there a way to disable the animation? I liked the previous Visibility toggle a bit better.

**Comment by wally2471** [comment]
Yeah the current fade animation is jank looking. I plan to attempt to port it to use CanvasGroup, which looks way nicer, eventually..

**Comment by violin-suzutsuki** [comment]
Setting MenuFadeTime to 0 will disable the fade animation

**Comment by violin-suzutsuki** [comment]
closed for now, may just remove the fade animation entirely in the future as i'm not really a fan of the code

note that for some reason the effect looks way better in my drawing lib ui library even though the code is doing the same thing?? maybe roblox transparency is weird
![image](https://user-images.githubusercontent.com/93684340/236152041-d270a48f-3ddd-4269-9782-72cdab5f1cd2.png)
