### ISSUE TITLE
Shift keybind is both left and right shift

### ISSUE THREAD

**Issue by sh0tx420** [violin-suzutsuki/LinoriaLib#35]
I want to set the default keybind of my menu to RightShift. When I try to set the default keybind to open the menu to LeftShift, pressing RightShift works too, but when I try to set the default keybind to RightShift, neither keybind works. Both LeftShift and RightShift are valid KeyCodes in the Roblox Creator Documentation.
This issue is the same with the Ctrl keys as well.

**Comment by sh0tx420** [comment]
By the way, is this an issue with the executor? Synapse is down at the moment so I can't check how it works there

**Comment by notpoiu** [comment]
Roblox UWP does not register RightShift, its a UWP issue.
