### ISSUE TITLE
mouse bug

### ISSUE THREAD

**Issue by Cryptnium** [violin-suzutsuki/LinoriaLib#38]
the custom mouse's position is not equal to the real mouse, ive had this issue happen in alot of scripts but with some theres no issue
![image](https://github.com/violin-suzutsuki/LinoriaLib/assets/110880998/d245845e-c84b-426f-a272-e8c2a608eb8f)

**Comment by MrKillingHunter** [comment]
disable custom cursor

**Comment by werzq** [comment]
> disable custom cursor
> 

could you tell how
