### ISSUE TITLE
Errors when loading config

### ISSUE THREAD

**Issue by kqmeta** [violin-suzutsuki/LinoriaLib#50]
![image](https://github.com/violin-suzutsuki/LinoriaLib/assets/94103858/a110cbe7-0d59-4312-ae71-c686c37363e1)
These are the errors I get when loading any config, including auto load. this makes the lib unusable for games that detect console outputs

The config loads fine, for the most part (only 1 keybind loads, no matter how many you assign)

**Comment by violin-suzutsuki** [comment]
1st error is because you have a Multi-select dropdown where you did Options.abc.Value = 'string' instead of Options.abc.Value[idx] = true/false
2nd error is coming from your script not LinoriaLib - specifically a slider callback
